<?php

/**
 * @file
 * Contains journal_devel.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function journal_devel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the journal_devel module.
    case 'help.page.journal_devel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Development extensions to the Journal install profile.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function journal_devel_theme() {
  return [
    'journal_devel' => [
      'render element' => 'children',
    ],
  ];
}
